version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/path/to/config/data:/data'
        environment:
            - OPENVPN_PROVIDER=PROTONVPN
            - OPENVPN_CONFIG=PROTONVPN_SERVER
            - OPENVPN_USERNAME=OPENVPN_USERNAME
            - OPENVPN_PASSWORD=OPENVPN_PASSWORD
            - LOCAL_NETWORK=LOCAL_NETWORK_CIDR
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn